// Mocks generated by Mockito 5.4.6 from annotations
// in knowledge_graph/test/domain/use_cases/organization_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:data_layer/data_layer.dart' as _i2;
import 'package:knowledge_graph/data/repositories/graph_repository.dart' as _i3;
import 'package:knowledge_graph/domain/models/thing.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSourceList_0<T> extends _i1.SmartFake implements _i2.SourceList<T> {
  _FakeSourceList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i3.GraphRepository {
  @override
  _i2.SourceList<_i4.Thing> get sourceList =>
      (super.noSuchMethod(
            Invocation.getter(#sourceList),
            returnValue: _FakeSourceList_0<_i4.Thing>(
              this,
              Invocation.getter(#sourceList),
            ),
            returnValueForMissingStub: _FakeSourceList_0<_i4.Thing>(
              this,
              Invocation.getter(#sourceList),
            ),
          )
          as _i2.SourceList<_i4.Thing>);

  @override
  DateTime Function() get getTime =>
      (super.noSuchMethod(
            Invocation.getter(#getTime),
            returnValue: () =>
                _FakeDateTime_1(this, Invocation.getter(#getTime)),
            returnValueForMissingStub: () =>
                _FakeDateTime_1(this, Invocation.getter(#getTime)),
          )
          as DateTime Function());

  @override
  _i2.Readiness get readiness =>
      (super.noSuchMethod(
            Invocation.getter(#readiness),
            returnValue: _i2.Readiness.ready,
            returnValueForMissingStub: _i2.Readiness.ready,
          )
          as _i2.Readiness);

  @override
  bool get isReady =>
      (super.noSuchMethod(
            Invocation.getter(#isReady),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNotReady =>
      (super.noSuchMethod(
            Invocation.getter(#isNotReady),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  set readiness(_i2.Readiness? value) => super.noSuchMethod(
    Invocation.setter(#readiness, value),
    returnValueForMissingStub: null,
  );

  @override
  String generateOperationId() =>
      (super.noSuchMethod(
            Invocation.method(#generateOperationId, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#generateOperationId, []),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.method(#generateOperationId, []),
            ),
          )
          as String);

  @override
  _i5.Future<_i4.Thing?> getById(String? id, {_i2.RequestDetails? details}) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id], {#details: details}),
            returnValue: _i5.Future<_i4.Thing?>.value(),
            returnValueForMissingStub: _i5.Future<_i4.Thing?>.value(),
          )
          as _i5.Future<_i4.Thing?>);

  @override
  _i5.Stream<_i4.Thing?> watch(String? id, {_i2.RequestDetails? details}) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [id], {#details: details}),
            returnValue: _i5.Stream<_i4.Thing?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i4.Thing?>.empty(),
          )
          as _i5.Stream<_i4.Thing?>);

  @override
  _i5.Future<(List<_i4.Thing>, Set<String>)> getByIds(
    Set<String>? ids, {
    _i2.RequestDetails? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [ids], {#details: details}),
            returnValue: _i5.Future<(List<_i4.Thing>, Set<String>)>.value((
              <_i4.Thing>[],
              <String>{},
            )),
            returnValueForMissingStub:
                _i5.Future<(List<_i4.Thing>, Set<String>)>.value((
                  <_i4.Thing>[],
                  <String>{},
                )),
          )
          as _i5.Future<(List<_i4.Thing>, Set<String>)>);

  @override
  _i5.Stream<(List<_i4.Thing>, Set<String>)> watchByIds(
    Set<String>? ids, {
    _i2.RequestDetails? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchByIds, [ids], {#details: details}),
            returnValue: _i5.Stream<(List<_i4.Thing>, Set<String>)>.empty(),
            returnValueForMissingStub:
                _i5.Stream<(List<_i4.Thing>, Set<String>)>.empty(),
          )
          as _i5.Stream<(List<_i4.Thing>, Set<String>)>);

  @override
  _i5.Future<List<_i4.Thing>> getItems({_i2.RequestDetails? details}) =>
      (super.noSuchMethod(
            Invocation.method(#getItems, [], {#details: details}),
            returnValue: _i5.Future<List<_i4.Thing>>.value(<_i4.Thing>[]),
            returnValueForMissingStub: _i5.Future<List<_i4.Thing>>.value(
              <_i4.Thing>[],
            ),
          )
          as _i5.Future<List<_i4.Thing>>);

  @override
  _i5.Stream<List<_i4.Thing>> watchList({_i2.RequestDetails? details}) =>
      (super.noSuchMethod(
            Invocation.method(#watchList, [], {#details: details}),
            returnValue: _i5.Stream<List<_i4.Thing>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<_i4.Thing>>.empty(),
          )
          as _i5.Stream<List<_i4.Thing>>);

  @override
  _i5.Future<_i4.Thing?> setItem(
    _i4.Thing? item, {
    _i2.RequestDetails? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setItem, [item], {#details: details}),
            returnValue: _i5.Future<_i4.Thing?>.value(),
            returnValueForMissingStub: _i5.Future<_i4.Thing?>.value(),
          )
          as _i5.Future<_i4.Thing?>);

  @override
  _i5.Future<List<_i4.Thing>> setItems(
    Iterable<_i4.Thing>? items, {
    _i2.RequestDetails? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setItems, [items], {#details: details}),
            returnValue: _i5.Future<List<_i4.Thing>>.value(<_i4.Thing>[]),
            returnValueForMissingStub: _i5.Future<List<_i4.Thing>>.value(
              <_i4.Thing>[],
            ),
          )
          as _i5.Future<List<_i4.Thing>>);

  @override
  _i5.Future<void> delete(String? id, {_i2.RequestDetails? details}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#details: details}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearForRequest(_i2.RequestDetails? details) =>
      (super.noSuchMethod(
            Invocation.method(#clearForRequest, [details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetReadiness() => super.noSuchMethod(
    Invocation.method(#resetReadiness, []),
    returnValueForMissingStub: null,
  );

  @override
  void markReady(dynamic obj) => super.noSuchMethod(
    Invocation.method(#markReady, [obj]),
    returnValueForMissingStub: null,
  );
}
