import 'package:logging/logging.dart';
import 'package:knowledge_graph/domain/models/creative_work.dart';
import 'package:knowledge_graph/domain/models/thing.dart';
import 'package:data_layer/data_layer.dart';

class CreateCreativeWorkUseCase {
  final Logger _log = Logger('CreateCreativeWorkUseCase');
  final Repository<Thing> _repository;

  CreateCreativeWorkUseCase(this._repository);

  Future<void> execute({
    required String name,
    CreativeWorkType workType = CreativeWorkType.creativeWork,
    String? description,
    String? url,
    List<String>? author,
  }) async {
    _log.info('Creating new creative work');
    final newWork = CreativeWork(
      id: '', // Will be generated by repository save binding
      workType: workType,
      name: name,
      description: description,
      url: url,
      author: author,
    );
    await _repository.setItem(newWork);

    _log.fine('CreativeWork saved successfully to repository');
  }
}

class EditCreativeWorkUseCase {
  final Logger _log = Logger('EditCreativeWorkUseCase');
  final Repository<Thing> _repository;

  EditCreativeWorkUseCase(this._repository);

  Future<void> execute(
    CreativeWork creativeWork, {
    String? name,
    CreativeWorkType? workType,
    String? description,
    String? url,
    List<String>? author,
  }) async {
    _log.info('Editing creative work: ${creativeWork.id}');
    final updatedWork = creativeWork.copyWith(
      name: name,
      workType: workType,
      description: description,
      url: url,
      author: author,
      clearDescription: description == null || description.trim().isEmpty,
      clearUrl: url == null || url.trim().isEmpty,
    );
    await _repository.setItem(updatedWork);

    _log.fine('CreativeWork updated successfully in repository');
  }
}

class DeleteCreativeWorkUseCase {
  final Logger _log = Logger('DeleteCreativeWorkUseCase');
  final Repository<Thing> _repository;

  DeleteCreativeWorkUseCase(this._repository);

  Future<void> execute(CreativeWork creativeWork) async {
    _log.info('Deleting creative work: ${creativeWork.id}');
    await _repository.delete(creativeWork.id);
    _log.fine('CreativeWork deleted from repository');
  }
}
