import 'package:logging/logging.dart';
import 'package:knowledge_graph/domain/models/organization.dart';
import 'package:knowledge_graph/data/repositories/organization_repository.dart';

class CreateOrganizationUseCase {
  final Logger _log = Logger('CreateOrganizationUseCase');
  final OrganizationRepository _organizationRepository;

  CreateOrganizationUseCase(this._organizationRepository);

  Future<void> execute({
    required String name,
    OrganizationType orgType = OrganizationType.organization,
    String? legalName,
    String? description,
    String? url,
  }) async {
    _log.info('Creating new organization');
    final newOrganization = Organization(
      id: '', // Will be generated by repository save binding
      orgType: orgType,
      name: name,
      legalName: legalName,
      description: description,
      url: url,
    );
    await _organizationRepository.setItem(newOrganization);
    _log.fine('Organization saved successfully to repository');
  }
}

class EditOrganizationUseCase {
  final Logger _log = Logger('EditOrganizationUseCase');
  final OrganizationRepository _organizationRepository;

  EditOrganizationUseCase(this._organizationRepository);

  Future<void> execute(
    Organization organization, {
    String? name,
    OrganizationType? orgType,
    String? legalName,
    String? description,
    String? url,
  }) async {
    _log.info('Editing organization: ${organization.id}');
    final updatedOrganization = organization.copyWith(
      name: name,
      orgType: orgType,
      legalName: legalName,
      description: description,
      url: url,
      clearLegalName: legalName == null || legalName.trim().isEmpty,
      clearDescription: description == null || description.trim().isEmpty,
      clearUrl: url == null || url.trim().isEmpty,
    );
    await _organizationRepository.setItem(updatedOrganization);
    _log.fine('Organization updated successfully in repository');
  }
}

class DeleteOrganizationUseCase {
  final Logger _log = Logger('DeleteOrganizationUseCase');
  final OrganizationRepository _organizationRepository;

  DeleteOrganizationUseCase(this._organizationRepository);

  Future<void> execute(Organization organization) async {
    _log.info('Deleting organization: ${organization.id}');
    await _organizationRepository.delete(organization.id);
    _log.fine('Organization deleted from repository');
  }
}
