import 'package:logging/logging.dart';
import 'package:knowledge_graph/domain/models/organization.dart';
import 'package:knowledge_graph/domain/models/thing.dart';
import 'package:data_layer/data_layer.dart';
import 'package:knowledge_graph/domain/models/person.dart';

Future<void> _addOrganizationToPeople(
  Repository<Thing> repository,
  String organizationId,
  Set<String> personIds,
) async {
  if (personIds.isEmpty) return;
  final (foundPeople, _) = await repository.getByIds(personIds);
  for (final person in foundPeople.whereType<Person>()) {
    if (!person.worksFor.contains(organizationId)) {
      final updatedWorksFor = List<String>.from(person.worksFor)
        ..add(organizationId);
      await repository.setItem(person.copyWith(worksFor: updatedWorksFor));
    }
  }
}

Future<void> _removeOrganizationFromPeople(
  Repository<Thing> repository,
  String organizationId,
  Set<String> personIds,
) async {
  if (personIds.isEmpty) return;
  final (foundPeople, _) = await repository.getByIds(personIds);
  for (final person in foundPeople.whereType<Person>()) {
    if (person.worksFor.contains(organizationId)) {
      final updatedWorksFor = List<String>.from(person.worksFor)
        ..remove(organizationId);
      await repository.setItem(person.copyWith(worksFor: updatedWorksFor));
    }
  }
}

class CreateOrganizationUseCase {
  final Logger _log = Logger('CreateOrganizationUseCase');
  final Repository<Thing> _repository;

  CreateOrganizationUseCase(this._repository);

  Future<void> execute({
    required String name,
    OrganizationType orgType = OrganizationType.organization,
    String? legalName,
    String? description,
    String? url,
    List<String>? employee,
  }) async {
    _log.info('Creating new organization');
    final newOrganization = Organization(
      id: '', // Will be generated by repository save binding
      orgType: orgType,
      name: name,
      legalName: legalName,
      description: description,
      url: url,
      employee: employee,
    );
    final savedOrganization = await _repository.setItem(newOrganization);

    if (savedOrganization != null && employee != null && employee.isNotEmpty) {
      await _addOrganizationToPeople(
        _repository,
        savedOrganization.id,
        employee.toSet(),
      );
    }

    _log.fine('Organization saved successfully to repository');
  }
}

class EditOrganizationUseCase {
  final Logger _log = Logger('EditOrganizationUseCase');
  final Repository<Thing> _repository;

  EditOrganizationUseCase(this._repository);

  Future<void> execute(
    Organization organization, {
    String? name,
    OrganizationType? orgType,
    String? legalName,
    String? description,
    String? url,
    List<String>? employee,
  }) async {
    _log.info('Editing organization: ${organization.id}');
    final updatedOrganization = organization.copyWith(
      name: name,
      orgType: orgType,
      legalName: legalName,
      description: description,
      url: url,
      employee: employee,
      clearLegalName: legalName == null || legalName.trim().isEmpty,
      clearDescription: description == null || description.trim().isEmpty,
      clearUrl: url == null || url.trim().isEmpty,
    );
    await _repository.setItem(updatedOrganization);

    if (employee != null) {
      final oldEmployee = organization.employee.toSet();
      final newEmployee = employee.toSet();

      await _addOrganizationToPeople(
        _repository,
        organization.id,
        newEmployee.difference(oldEmployee),
      );
      await _removeOrganizationFromPeople(
        _repository,
        organization.id,
        oldEmployee.difference(newEmployee),
      );
    }

    _log.fine('Organization updated successfully in repository');
  }
}

class DeleteOrganizationUseCase {
  final Logger _log = Logger('DeleteOrganizationUseCase');
  final Repository<Thing> _repository;

  DeleteOrganizationUseCase(this._repository);

  Future<void> execute(Organization organization) async {
    _log.info('Deleting organization: ${organization.id}');

    if (organization.employee.isNotEmpty) {
      await _removeOrganizationFromPeople(
        _repository,
        organization.id,
        organization.employee.toSet(),
      );
    }

    await _repository.delete(organization.id);
    _log.fine('Organization deleted from repository');
  }
}
