import 'package:logging/logging.dart';
import 'package:knowledge_graph/domain/models/person.dart';
import 'package:knowledge_graph/domain/models/thing.dart';
import 'package:data_layer/data_layer.dart';
import 'package:knowledge_graph/domain/models/organization.dart';

Future<void> _addPersonToOrganizations(
  Repository<Thing> repository,
  String personId,
  Set<String> orgIds,
) async {
  if (orgIds.isEmpty) return;
  final (foundOrgs, _) = await repository.getByIds(orgIds);
  for (final org in foundOrgs.whereType<Organization>()) {
    if (!org.employee.contains(personId)) {
      final updatedEmployee = List<String>.from(org.employee)..add(personId);
      await repository.setItem(org.copyWith(employee: updatedEmployee));
    }
  }
}

Future<void> _removePersonFromOrganizations(
  Repository<Thing> repository,
  String personId,
  Set<String> orgIds,
) async {
  if (orgIds.isEmpty) return;
  final (foundOrgs, _) = await repository.getByIds(orgIds);
  for (final org in foundOrgs.whereType<Organization>()) {
    if (org.employee.contains(personId)) {
      final updatedEmployee = List<String>.from(org.employee)..remove(personId);
      await repository.setItem(org.copyWith(employee: updatedEmployee));
    }
  }
}

Future<void> _addColleagues(
  Repository<Thing> repository,
  String personId,
  Set<String> colleagueIds,
) async {
  if (colleagueIds.isEmpty) return;
  final (foundPeople, _) = await repository.getByIds(colleagueIds);
  for (final person in foundPeople.whereType<Person>()) {
    if (!person.colleague.contains(personId)) {
      final updatedColleague = List<String>.from(person.colleague)
        ..add(personId);
      await repository.setItem(person.copyWith(colleague: updatedColleague));
    }
  }
}

Future<void> _removeColleagues(
  Repository<Thing> repository,
  String personId,
  Set<String> colleagueIds,
) async {
  if (colleagueIds.isEmpty) return;
  final (foundPeople, _) = await repository.getByIds(colleagueIds);
  for (final person in foundPeople.whereType<Person>()) {
    if (person.colleague.contains(personId)) {
      final updatedColleague = List<String>.from(person.colleague)
        ..remove(personId);
      await repository.setItem(person.copyWith(colleague: updatedColleague));
    }
  }
}

class CreatePersonUseCase {
  final Logger _log = Logger('CreatePersonUseCase');
  final Repository<Thing> _repository;

  CreatePersonUseCase(this._repository);

  Future<void> execute({
    String? givenName,
    String? familyName,
    String? jobTitle,
    String? birthDate,
    List<String>? worksFor,
    List<String>? colleague,
  }) async {
    _log.info('Creating new person');
    final newPerson = Person(
      id: '', // Will be generated by repository save binding
      givenName: givenName,
      familyName: familyName,
      jobTitle: jobTitle,
      birthDate: birthDate,
      worksFor: worksFor,
      colleague: colleague,
    );
    final savedPerson = await _repository.setItem(newPerson);

    if (savedPerson != null) {
      if (worksFor != null && worksFor.isNotEmpty) {
        await _addPersonToOrganizations(
          _repository,
          savedPerson.id,
          worksFor.toSet(),
        );
      }
      if (colleague != null && colleague.isNotEmpty) {
        await _addColleagues(_repository, savedPerson.id, colleague.toSet());
      }
    }

    _log.fine('Person saved successfully to repository');
  }
}

class EditPersonUseCase {
  final Logger _log = Logger('EditPersonUseCase');
  final Repository<Thing> _repository;

  EditPersonUseCase(this._repository);

  Future<void> execute(
    Person person, {
    String? givenName,
    String? familyName,
    String? jobTitle,
    String? birthDate,
    List<String>? worksFor,
    List<String>? colleague,
  }) async {
    _log.info('Editing person: ${person.id}');
    final updatedPerson = person.copyWith(
      givenName: givenName,
      familyName: familyName,
      jobTitle: jobTitle,
      birthDate: birthDate,
      worksFor: worksFor,
      colleague: colleague,
      clearGivenName: givenName == null || givenName.trim().isEmpty,
      clearFamilyName: familyName == null || familyName.trim().isEmpty,
      clearJobTitle: jobTitle == null || jobTitle.trim().isEmpty,
      clearBirthDate: birthDate == null || birthDate.trim().isEmpty,
    );
    await _repository.setItem(updatedPerson);

    if (worksFor != null) {
      final oldWorksFor = person.worksFor.toSet();
      final newWorksFor = worksFor.toSet();

      await _addPersonToOrganizations(
        _repository,
        person.id,
        newWorksFor.difference(oldWorksFor),
      );
      await _removePersonFromOrganizations(
        _repository,
        person.id,
        oldWorksFor.difference(newWorksFor),
      );
    }

    if (colleague != null) {
      final oldColleagues = person.colleague.toSet();
      final newColleagues = colleague.toSet();

      await _addColleagues(
        _repository,
        person.id,
        newColleagues.difference(oldColleagues),
      );
      await _removeColleagues(
        _repository,
        person.id,
        oldColleagues.difference(newColleagues),
      );
    }

    _log.fine('Person updated successfully in repository');
  }
}

class DeletePersonUseCase {
  final Logger _log = Logger('DeletePersonUseCase');
  final Repository<Thing> _repository;

  DeletePersonUseCase(this._repository);

  Future<void> execute(Person person) async {
    _log.info('Deleting person: ${person.id}');

    if (person.worksFor.isNotEmpty) {
      await _removePersonFromOrganizations(
        _repository,
        person.id,
        person.worksFor.toSet(),
      );
    }

    if (person.colleague.isNotEmpty) {
      await _removeColleagues(_repository, person.id, person.colleague.toSet());
    }

    await _repository.delete(person.id);
    _log.fine('Person deleted from repository');
  }
}
