import 'package:logging/logging.dart';
import 'package:knowledge_graph/domain/models/thing.dart';
import 'package:knowledge_graph/domain/models/thing_instance.dart';
import 'package:data_layer/data_layer.dart';

class CreateThingInstanceUseCase {
  final Logger _log = Logger('CreateThingInstanceUseCase');
  final Repository<Thing> _repository;

  CreateThingInstanceUseCase(this._repository);

  Future<void> execute({
    required String name,
    String? description,
    String? url,
  }) async {
    _log.info('Creating new thing instance');
    final newThing = ThingInstance(
      id: '', // Will be generated by repository save binding
      name: name,
      description: description,
      url: url,
    );
    await _repository.setItem(newThing);
    _log.fine('ThingInstance saved successfully to repository');
  }
}

class EditThingInstanceUseCase {
  final Logger _log = Logger('EditThingInstanceUseCase');
  final Repository<Thing> _repository;

  EditThingInstanceUseCase(this._repository);

  Future<void> execute(
    ThingInstance thing, {
    String? name,
    String? description,
    String? url,
  }) async {
    _log.info('Editing thing instance: ${thing.id}');
    final updatedThing = thing.copyWith(
      name: name,
      description: description,
      url: url,
      clearDescription: description == null || description.trim().isEmpty,
      clearUrl: url == null || url.trim().isEmpty,
    );
    await _repository.setItem(updatedThing);
    _log.fine('ThingInstance updated successfully in repository');
  }
}

class DeleteThingInstanceUseCase {
  final Logger _log = Logger('DeleteThingInstanceUseCase');
  final Repository<Thing> _repository;

  DeleteThingInstanceUseCase(this._repository);

  Future<void> execute(ThingInstance thing) async {
    _log.info('Deleting thing instance: ${thing.id}');
    await _repository.delete(thing.id);
    _log.fine('ThingInstance deleted from repository');
  }
}
