import 'package:knowledge_graph/domain/models/task.dart';
import 'package:knowledge_graph/domain/models/task_list.dart';
import 'package:knowledge_graph/domain/models/list_item.dart';
import 'package:knowledge_graph/data/repositories/task_repository.dart';
import 'package:knowledge_graph/data/repositories/task_list_repository.dart';

class CreateTaskUseCase {
  final TaskRepository _taskRepository;
  final TaskListRepository _taskListRepository;

  CreateTaskUseCase(this._taskRepository, this._taskListRepository);

  Future<void> execute(TaskList list, String taskName) async {
    var task = Task(
      id: '', // Will be generated by data_layer CreationBindings
      name: taskName,
      actionStatus: 'https://schema.org/PotentialActionStatus',
    );
    task = Task.bindings.save(task);
    final savedTask = await _taskRepository.setItem(task);

    // 2. Append reference to TaskList
    final items = List<ListItem>.from(list.itemListElement);
    items.add(ListItem(
      position: items.length + 1,
      item: savedTask!.id,
    ));

    final updatedList = list.copyWith(
      itemListElement: items,
      numberOfItems: items.length,
    );

    // 3. Save updated TaskList
    await _taskListRepository.setItem(updatedList);
  }
}

class DeleteTaskUseCase {
  final TaskRepository _taskRepository;
  final TaskListRepository _taskListRepository;

  DeleteTaskUseCase(this._taskRepository, this._taskListRepository);

  Future<void> execute(TaskList list, String taskId) async {
    // 1. Remove from TaskList and recompute positions
    final items = List<ListItem>.from(list.itemListElement)
      ..removeWhere((e) => e.item == taskId);
    
    for (int i = 0; i < items.length; i++) {
      items[i] = ListItem(position: i + 1, item: items[i].item);
    }

    final updatedList = list.copyWith(
      itemListElement: items,
      numberOfItems: items.length,
    );

    // 2. Save updated TaskList
    await _taskListRepository.setItem(updatedList);

    // 3. Delete Task from TaskRepository
    await _taskRepository.delete(taskId);
  }
}

class HydrateTaskListUseCase {
  final TaskRepository _taskRepository;

  HydrateTaskListUseCase(this._taskRepository);

  Future<List<Task>> execute(TaskList list) async {
    final sortedItems = List<ListItem>.from(list.itemListElement)
      ..sort((a, b) => a.position.compareTo(b.position));
    
    final taskIds = sortedItems.map((e) => e.item).toSet();
    if (taskIds.isEmpty) return [];

    final tasks = await _taskRepository.getByIds(taskIds);
    final taskMap = {for (var task in tasks.$1) task.id: task};

    return sortedItems
        .map((e) => taskMap[e.item])
        .whereType<Task>()
        .toList();
  }
}

class ToggleTaskStatusUseCase {
  final TaskRepository _taskRepository;

  ToggleTaskStatusUseCase(this._taskRepository);

  Future<void> execute(Task task) async {
    final newStatus = task.actionStatus == 'https://schema.org/CompletedActionStatus'
        ? 'https://schema.org/PotentialActionStatus'
        : 'https://schema.org/CompletedActionStatus';

    final updatedTask = task.copyWith(
      actionStatus: newStatus,
      endTime: newStatus == 'https://schema.org/CompletedActionStatus' 
          ? DateTime.now().toUtc().toIso8601String() 
          : null,
    );

    await _taskRepository.setItem(updatedTask);
  }
}
