import 'package:logging/logging.dart';
import 'package:knowledge_graph/domain/models/task.dart';
import 'package:knowledge_graph/domain/models/task_list.dart';
import 'package:knowledge_graph/domain/models/list_item.dart';
import 'package:knowledge_graph/domain/models/thing.dart';
import 'package:data_layer/data_layer.dart';

class CreateTaskUseCase {
  static final _log = Logger('CreateTaskUseCase');

  final Repository<Thing> _repository;

  CreateTaskUseCase(this._repository);

  Future<void> execute(
    TaskList list,
    String taskName, {
    String? description,
    List<String>? agent,
    List<String>? participant,
    List<String>? instrument,
  }) async {
    var task = Task(
      id: '', // Will be generated by data_layer CreationBindings
      name: taskName,
      description: description,
      actionStatus: TaskStatus.potential,
      agent: agent,
      participant: participant,
      instrument: instrument,
    );
    final savedTask = await _repository.setItem(task);
    _log.fine(
      'Task saved successfully to repository with ID: ${savedTask?.id}',
    );

    // 2. Append reference to TaskList
    final items = List<ListItem>.from(list.itemListElement);
    items.add(ListItem(position: items.length + 1, item: savedTask!.id));

    final updatedList = list.copyWith(
      itemListElement: items,
      numberOfItems: items.length,
    );

    // 3. Save updated TaskList
    await _repository.setItem(updatedList);
    _log.fine('TaskList updated and saved with new task reference');
  }
}

class DeleteTaskUseCase {
  static final _log = Logger('DeleteTaskUseCase');

  final Repository<Thing> _repository;

  DeleteTaskUseCase(this._repository);

  Future<void> execute(TaskList list, String taskId) async {
    // 1. Remove from TaskList and recompute positions
    final items = List<ListItem>.from(list.itemListElement)
      ..removeWhere((e) => e.item == taskId);

    for (int i = 0; i < items.length; i++) {
      items[i] = ListItem(position: i + 1, item: items[i].item);
    }

    final updatedList = list.copyWith(
      itemListElement: items,
      numberOfItems: items.length,
    );

    // 2. Save updated TaskList
    await _repository.setItem(updatedList);
    _log.fine('TaskList updated and saved without task reference');

    // 3. Delete Task from TaskRepository
    await _repository.delete(taskId);
    _log.fine('Task deleted from repository: $taskId');
  }
}

class HydrateTaskListUseCase {
  static final _log = Logger('HydrateTaskListUseCase');

  final Repository<Thing> _repository;

  HydrateTaskListUseCase(this._repository);

  Future<List<Task>> execute(TaskList list) async {
    final sortedItems = List<ListItem>.from(list.itemListElement)
      ..sort((a, b) => a.position.compareTo(b.position));

    final taskIds = sortedItems.map((e) => e.item).toSet();
    if (taskIds.isEmpty) return [];

    _log.fine('Hydrating ${taskIds.length} tasks for TaskList');
    final (foundTasks, _) = await _repository.getByIds(taskIds);
    final tasks = foundTasks.whereType<Task>().toList();
    final taskMap = {for (var task in tasks) task.id: task};

    return sortedItems.map((e) => taskMap[e.item]).whereType<Task>().toList();
  }
}

class ToggleTaskStatusUseCase {
  static final _log = Logger('ToggleTaskStatusUseCase');

  final Repository<Thing> _repository;

  ToggleTaskStatusUseCase(this._repository);

  Future<void> execute(Task task) async {
    final newStatus = task.actionStatus == TaskStatus.completed
        ? TaskStatus.potential
        : TaskStatus.completed;

    final updatedTask = task.copyWith(
      actionStatus: newStatus,
      endTime: newStatus == TaskStatus.completed
          ? DateTime.now().toUtc().toIso8601String()
          : null,
    );

    await _repository.setItem(updatedTask);
    _log.fine('Task status toggled and saved: ${updatedTask.id} -> $newStatus');
  }
}

class CreateTaskListUseCase {
  static final _log = Logger('CreateTaskListUseCase');

  final Repository<Thing> _repository;

  CreateTaskListUseCase(this._repository);

  Future<void> execute(String name, {String? description}) async {
    final list = TaskList(id: '', name: name, description: description);

    final savedList = await _repository.setItem(list);
    _log.fine(
      'TaskList saved successfully to repository with ID: ${savedList?.id}',
    );
  }
}

class DeleteTaskListUseCase {
  static final _log = Logger('DeleteTaskListUseCase');

  final Repository<Thing> _repository;

  DeleteTaskListUseCase(this._repository);

  Future<void> execute(TaskList list) async {
    // Delete all tasks in the list first
    for (final item in list.itemListElement) {
      await _repository.delete(item.item);
    }

    // Delete the list itself
    await _repository.delete(list.id);
    _log.fine('TaskList deleted from repository: ${list.id}');
  }
}

class EditTaskListUseCase {
  static final _log = Logger('EditTaskListUseCase');

  final Repository<Thing> _repository;

  EditTaskListUseCase(this._repository);

  Future<void> execute(
    TaskList list,
    String newName, {
    String? newDescription,
  }) async {
    final updatedList = list.copyWith(
      name: newName,
      description: newDescription,
    );

    await _repository.setItem(updatedList);
    _log.fine('TaskList updated successfully in repository: ${updatedList.id}');
  }
}

class EditTaskUseCase {
  static final _log = Logger('EditTaskUseCase');

  final Repository<Thing> _repository;

  EditTaskUseCase(this._repository);

  Future<void> execute(
    Task task,
    String newName, {
    String? newDescription,
    List<String>? newAgent,
    List<String>? newParticipant,
    List<String>? newInstrument,
  }) async {
    final updatedTask = task.copyWith(
      name: newName,
      description: newDescription,
      agent: newAgent,
      participant: newParticipant,
      instrument: newInstrument,
    );

    await _repository.setItem(updatedTask);
    _log.fine('Task updated successfully in repository: ${updatedTask.id}');
  }
}
